### ISSUE TITLE
Rails initializer not working

### ISSUE THREAD

**Issue by danielfmoreira** [amoniacou/pipedrive.rb#10]
When i add the rails initializer to skip sending the api token to new entity classes i still get the error:

`api_token should be set``

I'm calling the client like this (with thew initializer configured)

```ruby
client = Pipedrive::Person.new
person = client.find_by_id(1)
```

**Comment by simonoff** [comment]
Hi!

Have you created an initializer?

```ruby
Pipedrive.setup do |n|
  n.api_token = ENV['PIPEDRIVE_API_TOKEN']
end
```
